lyket: false
baseUrl: gnh.vibing.digital
linklyReferralLink: https://referral.foundations.design/gnh
muxVideo:
  muxVideoId: g3Usjfjtoif3af5vQA6nmsyG61Mbcd6LddMYBvA83800
  startTime: 90
  # muxVideoId: 024ddtK6yY2LMDzwCa017CjlLN01Cbs66hSyxBV01uyxSX8